### ISSUE TITLE
audio story

### ISSUE THREAD

**Issue by no-1ne** [devkrest/flutter_story_presenter#11]
Hello folks, 
thank you for the library, have a feature request to add ability to handle audio story..

**Comment by Kaival-Patel** [comment]
Thanks for the feature request @no-1ne. Our team will soon look into this. We are open to exploring various scenarios for audio stories, such as incorporating Audio on images or custom integrations.

**Comment by harshlet** [comment]
@alguintu 
### Audio Support Added in Beta

I've added audio support in the feature/audio branch. You can start using it now for testing and integration.

This version is concise and to the point, with a clear emphasis on the beta status and immediate usability.

### Added Audio Support Across Story Types

- Integrated audio playback functionality into image, text, and custom type stories.
- Users can now add and play audio files within any story type.
- Improved user experience by enabling richer, multimedia storytelling.

### Usage Instructions:
To include this feature in your project, add the following dependency to your pubspec.yaml:

```
dependencies:
  flutter_story_presenter:
    git:
      url: https://github.com/devkrest/flutter_story_presenter.git
      ref: feature/audio
```
Branch: feature/audio
GitHub: https://github.com/devkrest/flutter_story_presenter/tree/feature/audio
